package com.age.soc.services.exportaDados;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2022-01-04T09:15:39.836-02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://services.soc.age.com/", name = "ExportaDadosWs")
@XmlSeeAlso({ObjectFactory.class})
public interface ExportaDadosWs {

    @WebMethod
    @RequestWrapper(localName = "exportaDadosWs", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.exportaDados.ExportaDadosWs_Type")
    @ResponseWrapper(localName = "exportaDadosWsResponse", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.exportaDados.ExportaDadosWsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.age.soc.services.exportaDados.ExportaDadosWsVo exportaDadosWs(

        @WebParam(name = "arg0", targetNamespace = "")
        com.age.soc.services.exportaDados.ExportaDadosWsVo arg0
    ) throws WSException_Exception;
}
