package com.age.soc.services.exportaDados;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2022-01-04T09:15:39.858-02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "ExportaDadosWsService",
                  wsdlLocation = "https://ws1.soc.com.br/WSSoc/services/ExportaDadosWs?wsdl",
                  targetNamespace = "http://services.soc.age.com/")
public class ExportaDadosWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.soc.age.com/", "ExportaDadosWsService");
    public final static QName ExportaDadosWsPort = new QName("http://services.soc.age.com/", "ExportaDadosWsPort");
    static {
        URL url = null;
        try {
            url = new URL("https://ws1.soc.com.br/WSSoc/services/ExportaDadosWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExportaDadosWsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://ws1.soc.com.br/WSSoc/services/ExportaDadosWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExportaDadosWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExportaDadosWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExportaDadosWsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ExportaDadosWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExportaDadosWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExportaDadosWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ExportaDadosWs
     */
    @WebEndpoint(name = "ExportaDadosWsPort")
    public ExportaDadosWs getExportaDadosWsPort() {
        return super.getPort(ExportaDadosWsPort, ExportaDadosWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExportaDadosWs
     */
    @WebEndpoint(name = "ExportaDadosWsPort")
    public ExportaDadosWs getExportaDadosWsPort(WebServiceFeature... features) {
        return super.getPort(ExportaDadosWsPort, ExportaDadosWs.class, features);
    }

}
