package com.age.soc.services.socGed;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2022-01-04T09:16:17.285-02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "SocGedWsService",
                  wsdlLocation = "https://ws1.soc.com.br/WSSoc/SocGedWs?wsdl",
                  targetNamespace = "http://services.soc.age.com/")
public class SocGedWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.soc.age.com/", "SocGedWsService");
    public final static QName SocGedWsPort = new QName("http://services.soc.age.com/", "SocGedWsPort");
    static {
        URL url = null;
        try {
            url = new URL("https://ws1.soc.com.br/WSSoc/SocGedWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SocGedWsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://ws1.soc.com.br/WSSoc/SocGedWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SocGedWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SocGedWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SocGedWsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SocGedWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SocGedWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SocGedWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SocGedWs
     */
    @WebEndpoint(name = "SocGedWsPort")
    public SocGedWs getSocGedWsPort() {
        return super.getPort(SocGedWsPort, SocGedWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SocGedWs
     */
    @WebEndpoint(name = "SocGedWsPort")
    public SocGedWs getSocGedWsPort(WebServiceFeature... features) {
        return super.getPort(SocGedWsPort, SocGedWs.class, features);
    }

}
