package com.age.soc.services.socGed;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2022-01-04T09:16:17.205-02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://services.soc.age.com/", name = "SocGedWs")
@XmlSeeAlso({ObjectFactory.class})
public interface SocGedWs {

    @WebMethod
    @RequestWrapper(localName = "excluirSocGed", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.socGed.ExcluirSocGed")
    @ResponseWrapper(localName = "excluirSocGedResponse", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.socGed.ExcluirSocGedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.age.soc.services.socGed.GedWsRetornoVo excluirSocGed(

        @WebParam(name = "ExcluirGedWsVo", targetNamespace = "")
        com.age.soc.services.socGed.GedExcluirWsVo excluirGedWsVo
    );

    @WebMethod
    @RequestWrapper(localName = "incluirSocGed", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.socGed.IncluirSocGed")
    @ResponseWrapper(localName = "incluirSocGedResponse", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.socGed.IncluirSocGedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.age.soc.services.socGed.GedWsRetornoInclusaoVo incluirSocGed(

        @WebParam(name = "socged", targetNamespace = "")
        com.age.soc.services.socGed.IncluirGedWsVo socged
    );

    @WebMethod
    @RequestWrapper(localName = "alterarSocGed", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.socGed.AlterarSocGed")
    @ResponseWrapper(localName = "alterarSocGedResponse", targetNamespace = "http://services.soc.age.com/", className = "com.age.soc.services.socGed.AlterarSocGedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.age.soc.services.socGed.GedWsRetornoVo alterarSocGed(

        @WebParam(name = "socged", targetNamespace = "")
        com.age.soc.services.socGed.AlterarGedWsVo socged
    );
}
