
package com.age.soc.services.socGed;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2022-02-17T10:06:30.636-02:00
 * Generated source version: 3.3.6
 */

@WebFault(name = "WSException", targetNamespace = "http://services.soc.age.com/")
public class WSException_Exception extends Exception {

    private com.age.soc.services.socGed.WSException wsException;

    public WSException_Exception() {
        super();
    }

    public WSException_Exception(String message) {
        super(message);
    }

    public WSException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WSException_Exception(String message, com.age.soc.services.socGed.WSException wsException) {
        super(message);
        this.wsException = wsException;
    }

    public WSException_Exception(String message, com.age.soc.services.socGed.WSException wsException, java.lang.Throwable cause) {
        super(message, cause);
        this.wsException = wsException;
    }

    public com.age.soc.services.socGed.WSException getFaultInfo() {
        return this.wsException;
    }
}
