-- MySQL (dialeto do persistence.xml). Alternativa ao script SQL Server (TB_AVISO_APP.sql).
-- Com hibernate.hbm2ddl.auto=update a tabela também pode ser criada automaticamente.

CREATE TABLE IF NOT EXISTS TB_AVISO_APP (
    ID_AVISO_APP      BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE        BIGINT NOT NULL,
    TITULO            VARCHAR(255) NOT NULL,
    DESCRICAO         VARCHAR(2000) NULL,
    DATA_PUBLICACAO   DATETIME NOT NULL,
    IMAGEM            LONGBLOB NULL,
    REMOVIDO          TINYINT(1) NULL,
    DATA_REMOVIDO     DATETIME NULL,
    DATA_CRIACAO      DATETIME NOT NULL,
    DATA_ALTERACAO    DATETIME NOT NULL,
    VERSAO            INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_AVISO_APP_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE)
);

CREATE INDEX IDX_AVISO_APP_CLIENTE_DATA ON TB_AVISO_APP (ID_CLIENTE, DATA_PUBLICACAO);
