-- SQL Server. Para MySQL use TB_AVISO_APP_mysql.sql (dialeto configurado em persistence.xml).
-- Avisos do app mobile (novo). Executar no banco do cliente antes de usar a funcionalidade.
CREATE TABLE TB_AVISO_APP (
    ID_AVISO_APP      BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_CLIENTE        BIGINT NOT NULL,
    TITULO            VARCHAR(255) NOT NULL,
    DESCRICAO         VARCHAR(2000) NULL,
    DATA_PUBLICACAO   DATETIME NOT NULL,
    IMAGEM            VARBINARY(MAX) NULL,
    REMOVIDO          BIT NULL,
    DATA_REMOVIDO     DATETIME NULL,
    CONSTRAINT FK_AVISO_APP_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE)
);

CREATE INDEX IDX_AVISO_APP_CLIENTE_DATA ON TB_AVISO_APP (ID_CLIENTE, DATA_PUBLICACAO DESC);
