-- MySQL — tokens FCM por dispositivo do app mobile.
-- Com hibernate.hbm2ddl.auto=update a tabela também pode ser criada automaticamente.

CREATE TABLE IF NOT EXISTS TB_DEVICE_TOKEN (
    ID_DEVICE_TOKEN   BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PEDESTRE       BIGINT NOT NULL,
    FCM_TOKEN         VARCHAR(512) NOT NULL,
    PLATFORM          VARCHAR(20) NOT NULL,
    ATUALIZADO_EM     DATETIME NOT NULL,
    ATIVO             TINYINT(1) NOT NULL DEFAULT 1,
    APP_VERSION       VARCHAR(50) NULL,
    REMOVIDO          TINYINT(1) NULL,
    DATA_REMOVIDO     DATETIME NULL,
    DATA_CRIACAO      DATETIME NOT NULL,
    DATA_ALTERACAO    DATETIME NOT NULL,
    VERSAO            INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_DEVICE_TOKEN_PEDESTRE FOREIGN KEY (ID_PEDESTRE) REFERENCES TB_PEDESTRE(ID_PEDESTRE),
    CONSTRAINT UK_DEVICE_TOKEN_FCM UNIQUE (FCM_TOKEN)
);

CREATE INDEX IDX_DEVICE_TOKEN_PEDESTRE ON TB_DEVICE_TOKEN (ID_PEDESTRE);
