-- Integração Senior: hashes para diff local (carga completa + sincronização seletiva)
ALTER TABLE TB_PEDESTRE
  ADD COLUMN HASH_INTEGRACAO_SENIOR VARCHAR(64) NULL;

ALTER TABLE TB_PEDESTRE
  ADD COLUMN HASH_ESCALA_SENIOR VARCHAR(64) NULL;

ALTER TABLE TB_PEDESTRE
  ADD COLUMN USA_REF_SENIOR VARCHAR(1) NULL;

ALTER TABLE TB_PEDESTRE
  ADD COLUMN ESCALA_SENIOR_PENDENTE TINYINT(1) NULL;

ALTER TABLE TB_PEDESTRE
  ADD COLUMN DATA_ULTIMA_VERIFICACAO_ESCALA DATE NULL;
