-- Refresh diário de escala Senior (executar se TB_PEDESTRE_hash_senior_mysql.sql já foi aplicado)
ALTER TABLE TB_PEDESTRE
  ADD COLUMN ESCALA_SENIOR_PENDENTE TINYINT(1) NULL;

ALTER TABLE TB_PEDESTRE
  ADD COLUMN DATA_ULTIMA_VERIFICACAO_ESCALA DATE NULL;
