-- Matriz de permissões web por cliente/perfil (não afeta desktop)
CREATE TABLE IF NOT EXISTS TB_WEB_PERFIL_PERMISSAO (
    ID_WEB_PERFIL_PERMISSAO BIGINT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE BIGINT NULL,
    PERFIL VARCHAR(20) NOT NULL,
    CODIGO_PERMISSAO VARCHAR(80) NOT NULL,
    HABILITADO TINYINT(1) NOT NULL DEFAULT 1,
    REMOVIDO TINYINT(1) NULL DEFAULT 0,
    DATA_CRIACAO DATETIME NULL,
    DATA_ALTERACAO DATETIME NULL,
    DATA_REMOVIDO DATETIME NULL,
    PRIMARY KEY (ID_WEB_PERFIL_PERMISSAO),
    UNIQUE KEY UK_WEB_PERFIL_PERMISSAO (ID_CLIENTE, PERFIL, CODIGO_PERMISSAO),
    CONSTRAINT FK_WEB_PERFIL_PERMISSAO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
